{{- if .Values.imgproxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.imgproxy.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.imgproxy.environment | nindent 2 }}
{{- end }}