{{- if .Values.analytics.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.analytics.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.analytics.environment | nindent 2 }}
{{- end }}